# templates/alb-controller-values.yaml

# ------------------------------------------------------------------
# ALB Controller Helm Chart Values
# ------------------------------------------------------------------

# ğŸ’¡ .controller.args ì— ì „ë‹¬ë˜ëŠ” ì¸ìë¥¼ valuesë¥¼ í†µí•´ ëª…ì‹œí•©ë‹ˆë‹¤.
clusterName: "${cluster_name}"
awsRegion: "${region}"
awsVpcID: "${vpc_id}"